import { AuthProvider } from "@/app/provider"
import "./globals.css";

export const metadata = {
  title: "Chat-App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
